[config]
schemaVersion = "0.0.1"

[package]
namespace = "CommanderCat101"
name = "ContentSettings"
description = "A library for adding custom settings to Content Warning."
websiteUrl = "https://github.com/Commander-Cat101/ContentSettings"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "logo.png"
readme = "../README.md"
outdir = "../dist"

[[build.copy]]
source = "../LICENSE"
target = "/"

[[build.copy]]
source = "../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../Virality/bin/Release/netstandard2.1/MaxWasUnavailable.Virality.dll"
target = "/BepInEx/plugins/Virality/"

[publish]
communities = [ "content-warning", ]
repository = "https://thunderstore.io"
[publish.categories]
content-warning = [ "bepinex", "mods", "clientside", "serverside" ]