name: Publish (Dev)

on:
  push:
    branches: [ master ]

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4

      - name: Setup .NET Env
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.100"

      - name: Restore Solution
        run: |
          dotnet restore
          dotnet tool restore
          
      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Upload Thunderstore Artifact
        uses: actions/upload-artifact@v4
        with:
          name: thunderstore-build.zip
          path: dist/*.zip

      - name: Publishing to Thunderstore
        env:
          TCLI_AUTH_TOKEN: ${{ secrets.THUNDERSTORE_DEV_API_TOKEN }}
          TCLI_NAMESPACE: ${{ vars.THUNDERSTORE_PACKAGE_NAMESPACE == '' && '' || format('--package-namespace {0}', vars.THUNDERSTORE_PACKAGE_NAMESPACE) }}
        if: ${{ env.TCLI_AUTH_TOKEN != '' }}
        run: |
          dotnet tcli publish --config-path assets/thunderstore.toml --file dist/*.zip --repository https://thunderstore.dev --package-version "0.${{ github.run_number }}.0" ${{ env.TCLI_NAMESPACE }}
